spring.application.name=your-auth

spring.profiles.active=local

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.samuelmaia1_github.yourauth.domain.auth=DEBUG
logging.level.com.samuelmaia1_github.yourauth.domain.social=DEBUG
logging.level.com.samuelmaia1_github.yourauth.domain.refreshtoken=DEBUG
logging.level.com.samuelmaia1_github.yourauth.infra.security=DEBUG
logging.level.com.samuelmaia1_github.yourauth.infra.repository.adapter=DEBUG
logging.level.com.samuelmaia1_github.yourauth.presentation.controller.AuthController=DEBUG

server.forward-headers-strategy=framework

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD}

spring.data.redis.connect-timeout=5s
spring.data.redis.timeout=3s

spring.cache.type=redis
spring.cache.cache-names=activePlansV2,projectById,projectsByAccountId,currentByAccountId,authConfigByProjectAndAccount,passwordConfigByProjectId,passwordConfigByProjectAndAccount,accountSummaryByAccountId,accountUsageByOwnerAccountId,projectMembersByProjectId,userById,usersByProjectId,projectApiKeyById,projectApiKeysByProjectId
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=minha-api::
