spring.datasource.url=jdbc:h2:file:./.local-data/your-auth
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

api.security.access-token.secret=1234
api.security.access-token.issuer=your-auth-api
api.security.access-token.duration=PT6M

api.security.refresh-token.secret=123456
api.security.refresh-token.duration=P7D
